---
title: "Installing MATLAB"
---

NPS maintains a site license for MATLAB and Simulink. Follow the instructions on the MathWorks NPS portal to install the software: [mathworks.com/academia/tah-portal/naval-postgraduate-school](https://www.mathworks.com/academia/tah-portal/naval-postgraduate-school-30827417.html).

## Release

It is highly recommended that you install **Release 2026b** of MATLAB and Simulink. **Release 2025b or higher is required.**

It helps with debugging if everyone in the class is using the latest release.

- The online documentation from MathWorks is for the latest release, so older releases can behave differently from the documentation you find online.
- There are subtle gotchas that make code that works in one release problematic in another. For example, prior to R2024a, local functions had to be at the bottom of the file; see the [release notes](https://www.mathworks.com/help/matlab/release-notes.html#mw_694e8a08-77b2-4046-99a2-cf5a0f63cbb1). Release-dependent bugs like this can be infuriating and can be avoided by using the latest release.

## Toolboxes

MATLAB and Simulink products (toolboxes) are offered à la carte. The NPS license gives you access to [all the toolboxes](https://www.mathworks.com/products.html), but installing them all is overkill. Here are the requirements and recommendations. You can re-run the installer to add tools to your install if you find you are missing capabilities.

Required:

- Control System Toolbox
- Optimization Toolbox
- Signal Processing Toolbox
- Symbolic Math Toolbox

For reference, here is the release and toolbox listing from the instructor's install:

```
>> ver
-----------------------------------------------------------------------------------------------------------------
MATLAB Version: 26.2.0.3386108 (R2026b)
Operating System: Linux 6.8.0-138-generic #138~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  7 13:43:15 UTC  x86_64
Java Version: Java is not loaded
-----------------------------------------------------------------------------------------------------------------
MATLAB                                                Version 26.2        (R2026b)
Simulink                                              Version 26.2        (R2026b)
Aerospace Blockset                                    Version 26.2        (R2026b)
Aerospace Toolbox                                     Version 26.2        (R2026b)
Control System Toolbox                                Version 26.2        (R2026b)
Curve Fitting Toolbox                                 Version 26.2        (R2026b)
Deep Learning Toolbox                                 Version 26.2        (R2026b)
MATLAB Copilot                                        Version 26.2        (R2026b)
Navigation Toolbox                                    Version 26.2        (R2026b)
Optimization Toolbox                                  Version 26.2        (R2026b)
Statistics and Machine Learning Toolbox               Version 26.2        (R2026b)
```